default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project-planner_development

test:
  <<: *default
  database: project-planner_test

production:
  <<: *default
  database: project-planner_production
  username: project-planner
  password: <%= ENV['PROJECT-PLANNER_DATABASE_PASSWORD'] %>
