source "https://rubygems.org"

ruby "2.2.0"

gem "rails", "4.2.0"
gem "rails-api"
gem "pg"
gem "active_model_serializers", "0.8.3"

group :test, :development do
  gem "rspec-rails", "~> 3.0"
  gem "factory_girl_rails", "~> 4.0"
  gem "faker"
  gem "pry-rails"
end

group :test do
  gem "shoulda-matchers", require: false
end
